# Generated by Django 3.2.3 on 2021-05-16 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 18, 55, 57, 451937), verbose_name='Date Published'),
        ),
    ]
