# Generated by Django 3.2.3 on 2021-05-16 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_tutorial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 19, 12, 42, 2285), verbose_name='Date Published'),
        ),
    ]
